### ISSUE TITLE
Feature Request: Support for RGB Colors

### ISSUE THREAD

**Issue by arnoudkooi** [YECHUNAN/json-color-token#18]
Great extension.
Would you be willing to add support for RGB color numbers? i.e.:

` "--color--neutral": "79,86,100",`

**Comment by arnoudkooi** [comment]
This may be complex, I have a specific need to support ServiceNow, would it be ok if I publish a special ServiceNow fork, with credit to you?

**Comment by YECHUNAN** [comment]
@arnoudkooi You are more than welcome to fork the branch and create your own work based on it 😊. The main purpose of this extension is for generic token colorization. If you want to do add support for ServiceNow specific features (e.g. associate tokens/colors with ServiceNow concepts, trigger specific actions, etc.), you should create your own extension. Good luck!

**Comment by arnoudkooi** [comment]
Thanks, will keep you posted! 
(At this point adding something simple to [Monaco editor](https://twitter.com/sn_utils/status/1526714582781280257))
